### ISSUE TITLE
New ideas

### ISSUE THREAD

**Issue by Htepple** [LucGamesYT/MoreFeatures#1]
I think you can try to add totem or enchantment table + anvil. :3

**Comment by LucGamesYT** [comment]
enchantment and anvil works in nukkit. But the totem is a good idea!

**Comment by Htepple** [comment]
Anvil in nukkit has a lot of bugs, for example items disappearing.

**Comment by Htepple** [comment]
or "endless" experience.

**Comment by NycuRO** [comment]
@LucGamesYT  Anvil and Enchantment table not works. It's just packets added without check. Have a lot of bugs like duplication and there's no check/handle server properly.

**Comment by LucGamesYT** [comment]
Enchantment Table is fixed in the newest Nukkit version. But I can sit on the Anvil.

**Comment by LucGamesYT** [comment]
@Htepple The bug with the infinite experience I can not produce after.
And I can't reproduce the disappearance either.
