### ISSUE TITLE
ArmorStand bug

### ISSUE THREAD

**Issue by Htepple** [LucGamesYT/MoreFeatures#2]
I can not put armor on the stand. (Windows 10 edition + latest nukkit and 1 plugin)

**Comment by LucGamesYT** [comment]
Can you make a short video ?

**Comment by Htepple** [comment]
Yes of course

**Comment by Htepple** [comment]
Wait 20 min. pls

**Comment by LucGamesYT** [comment]
Okay

**Comment by LucGamesYT** [comment]
Could it also be that you have canceled the PlayerInteractEntityEvent?

**Comment by Htepple** [comment]
I has very bad internet connection. Now i'm uploading video on YouTube.

**Comment by LucGamesYT** [comment]
Okay, do you have canceled the PlayerInteractEntityEvent ?

**Comment by Htepple** [comment]
No, only 1 plugin.

**Comment by Htepple** [comment]
https://youtu.be/SONjUho1Qac

**Comment by LucGamesYT** [comment]
Look, for me works finde

https://youtu.be/HCS-cU1Q4lM

**Comment by Htepple** [comment]
Very interesting :/

**Comment by Htepple** [comment]
I will test it on linux

**Comment by LucGamesYT** [comment]
Use this jar https://ci.nukkitx.com/job/NukkitX/job/Nukkit/job/master/lastSuccessfulBuild/artifact/target/nukkit-1.0-SNAPSHOT.jar

**Comment by Htepple** [comment]
Lol, it works

**Comment by LucGamesYT** [comment]
Good news ^^
