### ISSUE TITLE
I don’t understand how this plugin works :(

### ISSUE THREAD

**Issue by skilastic** [LucGamesYT/MoreFeatures#3]
This was an amazing idea, But I cannot fully understand how this plugin works. Can someone please explain to me how to use this plugin? Do armor stand poses work? And how can i add items to an armor stand?

**Comment by Htepple** [comment]
Watch videos from 2nd issue.

**Comment by skilastic** [comment]
By what video are you talking about? I checked the other issue and I don’t see any links to videos

**Comment by skilastic** [comment]
I only see the “new ideas” issue

**Comment by LucGamesYT** [comment]
https://youtu.be/HCS-cU1Q4lM

**Comment by skilastic** [comment]
Omg thats amazing :), Thanks :)

**Comment by skilastic** [comment]
Wait, Its still not working for me. What are the controls you used to put the items on a armorstand, and the controls to pose it?

**Comment by skilastic** [comment]
I was in creative right-clicking the armorstand but it won’t work.

**Comment by LucGamesYT** [comment]
You can put armor with right click on the stand and for the pose you're gonna have to sneak

And use this new jar https://ci.nukkitx.com/job/NukkitX/job/Nukkit/job/master/lastSuccessfulBuild/artifact/target/nukkit-1.0-SNAPSHOT.jar

**Comment by skilastic** [comment]
Oh, I wasn’t updated. I will see if it works :)

**Comment by skilastic** [comment]
Cool, It works. But how to i add a head to the armorstand? Instead it just puts the head in the armorsstand’s hand.

**Comment by skilastic** [comment]
Nevermind
