### ISSUE TITLE
Custom Data of Armor Stands?

### ISSUE THREAD

**Issue by NycuRO** [LucGamesYT/MoreFeatures#4]
It's possible to Armor Stands have custom data like in PC to add entities flying and others? 

I think you know what i mean.

**Comment by LucGamesYT** [comment]
I don't know exactly, for floating items you don't need an armor stand in the pe

**Comment by NycuRO** [comment]
Not items, i mean custom entities.

**Comment by NycuRO** [comment]
https://www.spigotmc.org/resources/traincarts.39592/ 

Something like that

**Comment by LucGamesYT** [comment]
I don't think we can do this with ArmorStands. I think you have to do that with an EntityHuman
